# Generated by Django 4.2.16 on 2025-10-27 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThreeResources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="testerecursos/photos/", verbose_name="Foto"
                    ),
                ),
                (
                    "yes_no",
                    models.CharField(
                        choices=[("sim", "Sim"), ("nao", "Não")],
                        max_length=3,
                        verbose_name="Sim ou não",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "option",
                    models.CharField(
                        choices=[
                            ("a", "Opção A"),
                            ("b", "Opção B"),
                            ("c", "Opção C"),
                            ("d", "Opção D"),
                            ("e", "Opção E"),
                        ],
                        max_length=1,
                        verbose_name="Opções",
                    ),
                ),
            ],
            options={
                "verbose_name": "3 recursos",
                "verbose_name_plural": "3 recursos",
            },
        ),
    ]
