# Generated by Django 4.2.16 on 2025-10-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("non_superuser", "Não superusuários")],
                        max_length=32,
                        verbose_name="Escopo",
                    ),
                ),
                ("active", models.BooleanField(default=False, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Configuração de menu",
                "verbose_name_plural": "Configurações de menu",
                "ordering": ("scope", "-active", "pk"),
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Ordem")),
                (
                    "item_type",
                    models.CharField(
                        choices=[("model", "Modelo"), ("url", "Link personalizado")],
                        default="model",
                        max_length=16,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Nome do grupo em que o item será exibido. Deixe em branco para usar o nome do app.",
                        max_length=150,
                        verbose_name="Seção",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Texto exibido no menu. Deixe vazio para usar o padrão.",
                        max_length=150,
                        verbose_name="Rótulo",
                    ),
                ),
                (
                    "app_label",
                    models.CharField(
                        blank=True,
                        help_text="Utilize apenas para itens do tipo modelo.",
                        max_length=100,
                        verbose_name="App",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True,
                        help_text="Nome do modelo em letras minúsculas (ex.: especie).",
                        max_length=100,
                        verbose_name="Modelo",
                    ),
                ),
                (
                    "url_name",
                    models.CharField(
                        blank=True,
                        help_text="reverse() será aplicado. Informe namespaces se necessário.",
                        max_length=200,
                        verbose_name="Nome da URL",
                    ),
                ),
                (
                    "absolute_url",
                    models.URLField(
                        blank=True,
                        help_text="Utilizado como fallback quando a URL nomeada não for encontrada.",
                        verbose_name="URL absoluta",
                    ),
                ),
                (
                    "permission_codename",
                    models.CharField(
                        blank=True,
                        help_text="Opcional. Utilize o formato app_label.codename.",
                        max_length=150,
                        verbose_name="Permissão extra",
                    ),
                ),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="admin_menu.menuconfig",
                        verbose_name="Configuração",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de menu",
                "verbose_name_plural": "Itens de menu",
                "ordering": ("order", "pk"),
            },
        ),
        migrations.AddConstraint(
            model_name="menuconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("scope",),
                name="unique_active_menu_per_scope",
            ),
        ),
    ]
