# Generated by Django 4.2.16 on 2025-11-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemHealthConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "warn_cpu_load_per_core",
                    models.FloatField(
                        default=0.7,
                        help_text="Limite de atenção para carga média por núcleo (load1 / núcleos).",
                        verbose_name="Alerta de carga por núcleo",
                    ),
                ),
                (
                    "crit_cpu_load_per_core",
                    models.FloatField(
                        default=1.0,
                        help_text="Limite crítico para carga média por núcleo (load1 / núcleos).",
                        verbose_name="Crítico de carga por núcleo",
                    ),
                ),
                (
                    "warn_mem_used_pct",
                    models.PositiveIntegerField(
                        default=80,
                        help_text="Limite de atenção para percentual de memória utilizada.",
                        verbose_name="Alerta de uso de memória (%)",
                    ),
                ),
                (
                    "crit_mem_used_pct",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Limite crítico para percentual de memória utilizada.",
                        verbose_name="Crítico de uso de memória (%)",
                    ),
                ),
                (
                    "warn_disk_used_pct",
                    models.PositiveIntegerField(
                        default=80,
                        help_text="Limite de atenção para percentual de disco utilizado.",
                        verbose_name="Alerta de uso de disco (%)",
                    ),
                ),
                (
                    "crit_disk_used_pct",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Limite crítico para percentual de disco utilizado.",
                        verbose_name="Crítico de uso de disco (%)",
                    ),
                ),
                (
                    "cache_seconds",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Tempo de vida do cache das métricas antes de nova coleta.",
                        verbose_name="Tempo de cache (segundos)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de saúde do servidor",
                "verbose_name_plural": "Configurações de saúde do servidor",
            },
        ),
        migrations.CreateModel(
            name="SystemHealthPanel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Saúde do servidor",
                "verbose_name_plural": "Saúde do servidor",
            },
        ),
    ]
