# Generated by Django 4.2.16 on 2025-11-03 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("syshealth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessDashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Monitoramento de acessos",
                "verbose_name_plural": "Monitoramento de acessos",
                "permissions": (
                    ("view_access_dashboard", "Pode visualizar o dashboard de acessos"),
                ),
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="AccessSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "online_window_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Intervalo considerado para usuários online e métricas em minutos.",
                        verbose_name="Janela de usuários online (min)",
                    ),
                ),
                (
                    "auto_refresh_seconds",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Tempo entre atualizações automáticas do dashboard em segundos.",
                        verbose_name="Intervalo de auto atualização (s)",
                    ),
                ),
                (
                    "log_anonymous",
                    models.BooleanField(
                        default=True,
                        help_text="Desative para registrar apenas usuários autenticados.",
                        verbose_name="Registrar visitantes anônimos",
                    ),
                ),
                (
                    "log_non_get_requests",
                    models.BooleanField(
                        default=False,
                        help_text="Habilite para registrar requisições que não sejam GET.",
                        verbose_name="Registrar métodos não-GET",
                    ),
                ),
                (
                    "ignore_paths",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de prefixes de caminhos a ignorar (ex.: /static/).",
                        verbose_name="Caminhos ignorados",
                    ),
                ),
                (
                    "sampling_ratio",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="1 registra todos os acessos; valores maiores registram 1 a cada N acessos.",
                        verbose_name="Amostragem",
                    ),
                ),
                (
                    "retention_days",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Eventos com idade superior serão removidos pela limpeza agendada.",
                        verbose_name="Retenção (dias)",
                    ),
                ),
                (
                    "ignored_user_agents",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Substrings simples para identificar crawlers a ignorar.",
                        verbose_name="User agents ignorados",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de monitoramento de acesso",
                "verbose_name_plural": "Configurações de monitoramento de acesso",
            },
        ),
        migrations.CreateModel(
            name="AccessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.CharField(
                        blank=True, max_length=45, verbose_name="Endereço IP"
                    ),
                ),
                ("path", models.CharField(max_length=512, verbose_name="Caminho")),
                (
                    "referrer",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Origem (referer)"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=256, verbose_name="User agent"
                    ),
                ),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="Origem: admin?"),
                ),
                ("created_date", models.DateField(verbose_name="Data do acesso")),
                (
                    "created_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora do acesso"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="access_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de acesso",
                "verbose_name_plural": "Eventos de acesso",
                "ordering": ("-created_date", "-created_time", "-pk"),
                "permissions": (
                    ("view_access_event", "Pode visualizar eventos de acesso"),
                ),
                "default_permissions": (),
                "indexes": [
                    models.Index(fields=["created_date"], name="ops_access_date_idx"),
                    models.Index(
                        fields=["created_date", "created_time"],
                        name="ops_access_datetime_idx",
                    ),
                    models.Index(fields=["user"], name="ops_access_user_idx"),
                    models.Index(fields=["ip_address"], name="ops_access_ip_idx"),
                    models.Index(fields=["is_admin"], name="ops_access_admin_idx"),
                ],
            },
        ),
    ]
