# Generated by Django 4.2.16 on 2025-11-03 20:47

from django.db import migrations


def create_settings_and_permissions(apps, schema_editor):
    AccessSettings = apps.get_model("syshealth", "AccessSettings")
    AccessSettings.objects.get_or_create(
        defaults={
            "ignore_paths": [
                "/static/",
                "/media/",
                "/admin/jsi18n/",
                "/admin/ops/access-dashboard",
                "/admin/ops/",
                "/.well-known/appspecific/com.chrome.devtools.json",
                "/admin/syshealth/",
            ],
            "log_anonymous": True,
            "log_non_get_requests": False,
            "sampling_ratio": 1,
            "retention_days": 90,
        }
    )

    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")

    dashboard_ct, _ = ContentType.objects.get_or_create(
        app_label="ops", model="access_dashboard"
    )
    event_ct, _ = ContentType.objects.get_or_create(app_label="ops", model="access_event")

    Permission.objects.get_or_create(
        content_type=dashboard_ct,
        codename="view_access_dashboard",
        defaults={"name": "Pode visualizar o dashboard de acessos"},
    )
    Permission.objects.get_or_create(
        content_type=event_ct,
        codename="view_access_event",
        defaults={"name": "Pode visualizar eventos de acesso"},
    )

    group, _ = Group.objects.get_or_create(name="system_dashboard_viewers")
    perms = Permission.objects.filter(
        content_type__app_label="ops",
        codename__in=["view_access_dashboard", "view_access_event"],
    )
    group.permissions.add(*perms)


def remove_settings_and_permissions(apps, schema_editor):
    AccessSettings = apps.get_model("syshealth", "AccessSettings")
    AccessSettings.objects.all()  # ensure model loaded for migrations

    ContentType = apps.get_model("contenttypes", "ContentType")
    Permission = apps.get_model("auth", "Permission")
    Group = apps.get_model("auth", "Group")

    try:
        group = Group.objects.get(name="system_dashboard_viewers")
    except Group.DoesNotExist:
        group = None
    if group:
        group.permissions.remove(
            *group.permissions.filter(
                content_type__app_label="ops",
                codename__in=["view_access_dashboard", "view_access_event"],
            )
        )

    Permission.objects.filter(
        content_type__app_label="ops",
        codename__in=["view_access_dashboard", "view_access_event"],
    ).delete()
    ContentType.objects.filter(app_label="ops", model__in=["access_dashboard", "access_event"]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("syshealth", "0002_accessdashboard_accesssettings_accessevent"),
    ]

    operations = [
        migrations.RunPython(create_settings_and_permissions, remove_settings_and_permissions),
    ]
